### ISSUE TITLE
Device dies; does not trigger disconnection screen

### ISSUE THREAD

**Issue by skspiers** [engagementgamelab/AtStake_v2#13]
If a player's device loses charge and dies during the middle of a game, the other players do not get a "player disconnected" screen. They are able to continue playing normally. 

To recreate this: let one of the devices die during gameplay.

**Comment by jayvachon** [comment]
"dies" as in no more battery?

**Comment by skspiers** [comment]
yes

**Comment by jayvachon** [comment]
cool. gonna let this one go. i think players will understand.
