### ISSUE TITLE
The artist character's "pitch" and "deliberate" counter screens missing text

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/AtStake_v2#2]
![img_0025](https://cloud.githubusercontent.com/assets/11821504/14295909/8ef58f78-fb45-11e5-83f4-bfe7b3d5ba20.PNG)
The description sentence is cut off, and it should have "Agenda" title and "funding for public art" above the double coin icon

**Comment by jayvachon** [comment]
this happens because there's too much text to display on the screen - it'll be fixed after I've done another pass on the ui
