### ISSUE TITLE
Random game "forrest" shows up in joining options - doesn't exist

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/AtStake_v2#4]
1. player1 hosts game
2. player2 or 3 selects "join" 
3. "forrest" shows up as option with actual game name
4. if "forrest" is selected and "go" is pressed, nothing happens
5. if the actual game is then selected and "go" is pressed, nothing happens
6. player2 or 3 can go back and select "join" again to select the actual game

**Comment by jayvachon** [comment]
you're hearing mine from the other room :)
