### ISSUE TITLE
If host leaves game while other players are delayed connecting - UI overlap 

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/AtStake_v2#5]
1. player1 hosts, player 2 joins - on delay, host leaves game
2. player2 screen has UI overlap from joining:
   ![img_0027](https://cloud.githubusercontent.com/assets/11821504/14326747/623dd2d4-fbfd-11e5-8a1d-daea4bc17359.PNG)
3. if player1 hosts again and player2 joins game, multiples in the game screen:
   ![img_0028](https://cloud.githubusercontent.com/assets/11821504/14326769/72b21760-fbfd-11e5-8204-f997a9f1cc90.PNG)

**Comment by jayvachon** [comment]
closing because network system has been replaced
