### ISSUE TITLE
UI on IPhone - crammed lower bar

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/AtStake_v2#9]
![img_0001](https://cloud.githubusercontent.com/assets/11821504/14649847/e36adfd0-0636-11e6-9517-d46ed2ccd169.PNG)

**Comment by jayvachon** [comment]
this only happens on the ipod right?

**Comment by esalling23** [comment]
yes, only for ipod -- also point cramming

![img_0004](https://cloud.githubusercontent.com/assets/11821504/14653354/a53d3766-0646-11e6-996a-f4f569e33cbe.PNG)
